# install.ps1 - drop a profile router into the consumer's project root
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Profile,
    [string]$SubmodulePath = ".ai/profiles",
    [string]$RouterName = "AGENTS.md"
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot  = Split-Path -Parent $scriptDir
$profileDir = Join-Path $repoRoot "!profiles/$Profile"

if (-not (Test-Path -LiteralPath $profileDir)) {
    throw "Profile '$Profile' not found at $profileDir"
}

$consumerRoot = (Get-Location).Path
$submoduleFull = Join-Path $consumerRoot $SubmodulePath

# Sanity: submodule must be present at the expected path
if (-not (Test-Path -LiteralPath (Join-Path $submoduleFull "!profiles/$Profile/AGENTS.md"))) {
    throw "Expected profile not visible at $submoduleFull\!profiles\$Profile\AGENTS.md. Did you run 'git submodule update --init --recursive' ?"
}

$routerPath = Join-Path $consumerRoot $RouterName
$relativeProfile = ($SubmodulePath -replace '\\','/') + "/!profiles/$Profile/AGENTS.md"

$content = @"
# AI Assistant Router

This project uses the AI profiles submodule. All conventions, agents, and skills
live in `$relativeProfile`. Do not duplicate them here.

Full Android profile entry point: $relativeProfile
"@

# Don't clobber an existing router that wasn't generated by us
if (Test-Path -LiteralPath $routerPath) {
    $existing = Get-Content -LiteralPath $routerPath -Raw
    if ($existing -notmatch '# AI Assistant Router') {
        throw "Refusing to overwrite $routerPath - it is not a router we wrote. Move it aside and re-run."
    }
}

Set-Content -LiteralPath $routerPath -Value $content -Encoding UTF8
Write-Host "Wrote $routerPath -> $relativeProfile" -ForegroundColor Green